### ISSUE TITLE
Write english version

### ISSUE THREAD

**Issue by fernahh** [fernahh/frontendpath#7]
:uk: Hey guys. I created this issue to plan the english version of Front-end Path. :uk: 

![english](https://cloud.githubusercontent.com/assets/2369851/9569720/c5899f96-4f49-11e5-973d-e2b1c0136d68.gif)
## Tasks
- [x] Configure [Middleman I18n](https://middlemanapp.com/advanced/localization/) - @fernahh
- [x] Add flags to indicate current language - @fernahh
## Topics
- [x] Introduction ([pt-br](https://github.com/fernahh/frontendpath/blob/master/source/index.html.erb)) - @BuKinoshita 
- [ ] Accessibility ([pt-br](https://github.com/fernahh/frontendpath/blob/master/source/guia/a-acessibilidade.html.md)) - @BuKinoshita 
- [ ] Semantics ([pt-br](https://github.com/fernahh/frontendpath/blob/master/source/guia/a-semantica.html.md)) - @lcandiago
- [x] CSS ([pt-br](https://github.com/fernahh/frontendpath/blob/master/source/guia/o-css.html.md)) - @idmarjr 
- [ ] JavaScript ([pt-br](https://github.com/fernahh/frontendpath/blob/master/source/guia/o-javascript.html.md)) - @rwillrich 

**If each of you pick a topic, this process would be amazing!**

(cc @rwillrich @Jesm @idmarjr @andersonweb @lcandiago)

Thanks!

**Comment by idmarjr** [comment]
Gimme the CSS!
I'm going start it on Tuesday. 😬

**Comment by andersoonweb** [comment]
unfortunately, I am not good in English :warning:

**Comment by fernahh** [comment]
Thanks, @idmarjr! 

Sorry, @andersonweb. Thank you anyway.

**Comment by andersoonweb** [comment]
I'll accompanying perhaps not roll some help: P @fernahh !

**Comment by rwillrich** [comment]
I'll translate the JavaScript part.

**Comment by fernahh** [comment]
Thanks, @rwillrich! :smile:

**Comment by lcandiago** [comment]
I'll pick the Semantics page!

**Comment by fernahh** [comment]
Thanks, @lcandiago! o/

**Comment by idmarjr** [comment]
@fernahh Anny news about  [Middleman I18](https://middlemanapp.com/advanced/localization/)?
I would like to commit it directly to the final structure if it possible. :sweat_smile:

**Comment by fernahh** [comment]
@idmarjr I created a branch for this work. Send the PR for it, ok?

https://github.com/fernahh/frontendpath/tree/I18n

**Comment by idmarjr** [comment]
Awesome! Thanks @fernahh

**Comment by bukinoshita** [comment]
I'll be doing the `Introduction` and `Accessibility`.

How do I suppose to do that? Should I override the Portuguese version or create a new file `index-en.html.erb`

**Comment by fernahh** [comment]
@BuKinoshita I created a branch for [I18n](https://github.com/fernahh/frontendpath/tree/I18n). Make checkout this branch. Example:

- [Introduction](https://github.com/fernahh/frontendpath/blob/I18n/source/en/index.html.erb)
- [Accessibility](https://github.com/fernahh/frontendpath/blob/I18n/source/guide/the-accessibility.html.md)

Thanks @BuKinoshita!

**Comment by idmarjr** [comment]
@BuKinoshita In my fork I copy/past the pt-br version to the same file in i18n branch and make the first commit of it (https://github.com/idmarjr/frontendpath/commit/9e26bcb31bf2109367a0635da48df2068b62d8f4).

I use it as reference to translate.
Beside that I'm trying to make one commit to each section or topic of the content, this way is easy to find a specific translation if needed. Ex: https://github.com/idmarjr/frontendpath/commit/f77bb231f00ec486a1387ff4f4117d4d1f02013c

**Comment by bukinoshita** [comment]
@idmarjr ty

**Comment by idmarjr** [comment]
:smile:

**Comment by fernahh** [comment]
Look guys! I created it with [CSS Filters](https://github.com/fernahh/frontendpath/commit/d058a93ce3e841b92671b5cf4b1323592e091188#diff-14c0d6893550037945d14d24b3dd5b15R37)! :heart_eyes: 

![I18n Flags](https://cloud.githubusercontent.com/assets/2369851/10561618/c0b1df18-7507-11e5-857e-b99c11017c02.png)

**Comment by bukinoshita** [comment]
@fernahh ohh, cool! :sunglasses:

**Comment by bukinoshita** [comment]
# Just some thoughts ...

Are we sticking with `A correct path to Front-end Development` or should we change to `The right path to Front-end Development`?

Also, instead of using `the-accessibility.html.md`, we should use `accessibility.html.md`. Get rid off the **the**.

**Comment by fernahh** [comment]
@BuKinoshita I believe that there are other paths to follow. I also think that this is not the absolute truth about where to start. Right? :)

**Comment by lhonardo** [comment]
have something left to be translated?

**Comment by rwillrich** [comment]
@lorbicki I started to translate the JavaScript session but haven't had much time. You can see what is still missing here #8.
